# Generated by Django 5.1.6 on 2025-03-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
